### ISSUE TITLE
sed fails on macos because of missing option -e bevor the script

### ISSUE THREAD

**Issue by medienagent-user** [ddev/ddev-redis-7#24]
ddev get ddev-redis-7 fails.
On macos sed fails, when "-e" is missing before the script. 
Instead of 

```
sed -i "s/REPLACE_ME/${DDEV_SITENAME}/g" redis/snapshots.conf
```

on mac to run it has to be 

```
sed -i -e "s/REPLACE_ME/${DDEV_SITENAME}/g" redis/snapshots.conf
```

On Linux both versions work.

<img width="531" alt="Bildschirmfoto 2023-10-18 um 19 05 57" src="https://github.com/ddev/ddev-redis-7/assets/33146807/026da420-fe41-4733-9f2e-d044f8d529f5">

**Comment by Morgy93** [comment]
Just ran into this issue. I hope it can be resolved soon.
Thanks for providing the PR to it. 🙌

**Comment by axmue** [comment]
I messed up my pull request. Sorry. The first commit was the correct one.
