### ISSUE TITLE
ddev-redis-7 doesn't work with v1.23.0

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-redis-7#27]
I see that tests against DDEV HEAD have been failing for quite some time, and now that v1.23.0 is released, all tests are failing.

https://github.com/ddev/ddev-redis-7/actions

From Discord, https://discord.com/channels/664580571770388500/1068592266752573440/1230052601404592170

> Has anyone seen the error * error decoding 'services[redis].deploy.resources.limits.cpus': unexpected value type int for cpus since the latest update of ddev to v1.23.0 ? Since this update the redis addon fails. (ddev/ddev-redis-7)

Could you please get this fixed up? If you're not getting emails about failed tests, it would be great to sort that out as well, thanks!

**Comment by rfay** [comment]
Related:
* https://github.com/oblakstudio/ddev-minio/issues/35

**Comment by stasadev** [comment]
Fixed in #28.
